# COMPUTER VISION ASSIGNMENT-2
## AMOGH GARG - 2020UCO1688

`Question-1` : Take a patch of size 5*5 with random intensity values. Apply the x-kernel [-1,0,1] and y-kernel [-1,0,1]^T to get the first order gradient in both the dimensions.

In [1]:
import numpy as np

# create a 5x5 patch with random intensity values
patch = [[0,0,1,4,9],[1,0,0,1,11],[1,4,9,12,16],[3,8,11,14,16],[8,10,15,16,20]]

# apply x-kernel [-1,0,1]
x_kernel = np.array([-1, 0, 1])
x_gradient = np.apply_along_axis(lambda m: np.convolve(m, x_kernel, mode='same'), axis=1, arr=patch)

# apply y-kernel [-1,0,1]^T
y_kernel = np.array([-1, 0, 1]).reshape((3, 1))
y_gradient = np.apply_along_axis(lambda m: np.convolve(m, y_kernel.flatten(), mode='same'), axis=0, arr=patch)

print("Patch:\n", patch)
print("\nX-gradient:\n", x_gradient)
print("\nY-gradient:\n", y_gradient)

Patch:
 [[185 208  36 162 243]
 [ 14  68 188 151 178]
 [202 169 110  59  24]
 [195  29 180  20 201]
 [119 239  33  81 124]]

X-gradient:
 [[-208  149   46 -207  162]
 [ -68 -174  -83   10  151]
 [-169   92  110   86   59]
 [ -29   15    9  -21   20]
 [-239   86  158  -91   81]]

Y-gradient:
 [[ -14  -68 -188 -151 -178]
 [ -17   39  -74  103  219]
 [-181   39    8  131  -23]
 [  83  -70   77  -22 -100]
 [ 195   29  180   20  201]]


`Question-2` : Compute the Harris matrix from these computed gradients.

In [2]:
# Define the patch of size 5x5 with random intensity values
patch = [[0,0,1,4,9],[1,0,0,1,11],[1,4,9,12,16],[3,8,11,14,16],[8,10,15,16,20]]

# Compute the first order gradients in x and y directions using the Sobel operator
Ix = np.gradient(patch, axis=0)
Iy = np.gradient(patch, axis=1)

# Compute the elements of the structure tensor using a Gaussian window as the weight function
sigma = 1.0  # standard deviation of the Gaussian window
weight = np.array([[np.exp(-((i-2)**2 + (j-2)**2) / (2*sigma**2)) for j in range(5)] for i in range(5)])
M11 = weight * Ix**2
M12 = weight * Ix * Iy
M22 = weight * Iy**2

# Compute the Harris matrix by summing over the structure tensors of all pixels
H = np.zeros((2, 2))
for i in range(5):
    for j in range(5):
        H += np.array([[M11[i,j], M12[i,j]], [M12[i,j], M22[i,j]]])

print("Harris Matrix:")
print(H)

Harris Matrix:
[[100.76348767  74.52315352]
 [ 74.52315352  77.6409883 ]]


`Question-3` : Compute the Eigen values and the Eigen vectors for the computed Harris matrix.

In [5]:
# Define the Harris matrix

# Compute the eigenvalues and eigenvectors
eigvals, eigvecs = np.linalg.eig(H)

# Print the results
print("Eigenvalues:", eigvals)
print("Eigenvectors:", eigvecs)

Eigenvalues: [170.23681998  13.76318002]
Eigenvectors: [[ 0.95342256 -0.3016379 ]
 [ 0.3016379   0.95342256]]


`Question-4` : Based on the computed Eigen values of the Harris matrix, identify whether the output patch is, an edge, a corner, or a flat surface.

Since both eigen values are large (>>0) therefore the patch corresponds to a **corner**.